services:
  - type: web
    name: seo-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false